# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Azure Pipelines
  demands: npm
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '1.x'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'qp-ampd-app'
    verbose: false

- task: Npm@1
  displayName: 'npm run client:prep'
  inputs:
    command: custom
    workingDir: 'qp-ampd-app'
    verbose: false
    customCommand: 'run client:prep'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
