/*/
  *  ┌────────────────────────────┐
  *  │ |> Redux - Action Types    │
  *  └────────────────────────────┘
/*/
 
//~~Reducers
export const areaQueryTypes = {
  AREA_QUERY_PUTS: "AREA_QUERY_PUTS",
  AREA_QUERY_PUSH: "AREA_QUERY_PUSH",
  AREA_QUERY_READY: "AREA_QUERY_READY",
  AREA_QUERY_SEND: "AREA_QUERY_SEND",
  AREA_QUERY_DONE: "AREA_QUERY_DONE",
  AREA_QUERY_FAIL: "AREA_QUERY_FAIL",
  AREA_QUERY_STATS: "AREA_QUERY_STATS"
};
//~~Security
export const securityTokenTypes = {
  SECURITY_TOKEN_CHECK: "SECURITY_TOKEN_CHECK",
  SECURITY_TOKEN_SET: "SECURITY_TOKEN_SET",
  SECURITY_TOKEN_DECRYPT: "SECURITY_TOKEN_DECRYPT",
  SECURITY_TOKEN_FAIL: "SECURITY_TOKEN_FAIL",
  SECURITY_TOKEN_SUCCESS: "SECURITY_TOKEN_SUCCESS",
};
//~~Sagas
export const areaQueryTypesSaga = {
  AREA_QUERY_PUTS_SAGA: "AREA_QUERY_PUTS_SAGA",
  AREA_QUERY_PUSH_SAGA: "AREA_QUERY_PUSH_SAGA",
  AREA_QUERY_READY_SAGA: "AREA_QUERY_READY_SAGA",
  AREA_QUERY_SEND_SAGA: "AREA_QUERY_SEND_SAGA",
  AREA_QUERY_DONE_SAGA: "AREA_QUERY_DONE_SAGA",
  AREA_QUERY_FAIL_SAGA: "AREA_QUERY_FAIL_SAGA",
  AREA_QUERY_STATS_SAGA: "AREA_QUERY_STATS_SAGA"
};
